/** Superfície pública do módulo `aplicacao/organizacao` (ADR-0006, regra 3). */
export { criarOrganizacao } from "./criar-organizacao";
export { contarAreas, contarCategorias, listarAreas, listarCategorias, listarPedidosDeEntrada } from "./consultas";
export { pedirEntrada, type ComandoDePedirEntrada } from "./pedir-entrada";
export {
  lerConvite,
  type ConviteLido,
  type QuemAbreOConvite,
  type SituacaoDoConvite,
} from "./ler-convite";
export {
  aprovarPedidoDeEntrada,
  recusarPedidoDeEntrada,
  type DecisaoDeAprovacao,
  type DecisaoDeRecusa,
} from "./decidir-pedido-de-entrada";
export {
  cadastrarVinculo,
  corrigirVinculo,
  listarImpedimentosDeRemocao,
  listarResponsabilidadesEmAberto,
  listarVinculos,
  removerVinculo,
  revogarVinculo,
  verVinculo,
} from "./vinculos";
export {
  aceitarConvitePessoal,
  garantirConvitePessoal,
  lerConvitePessoal,
  ligarContaAoConvitePessoal,
  renovarConvitePessoal,
  type ConvitePessoalLido,
  type SituacaoDoConvitePessoal,
} from "./convite-pessoal";
export { apagarEtiqueta, atribuirEtiqueta, criarEtiqueta, listarEtiquetas, tirarEtiqueta } from "./etiquetas";
export {
  alterarConfiguracao,
  corrigirArea,
  corrigirCategoria,
  corrigirOrganizacao,
  criarArea,
  criarCategoria,
  lerConfiguracao,
  lerRegrasDaOrganizacao,
  lerRotulosDoSolicitante,
  reordenarAreas,
  reordenarCategorias,
  type ComandoDeAlteracaoDeConfiguracao,
  type ComandoDeCorrecaoDeArea,
  type ComandoDeCorrecaoDeCategoria,
  type ComandoDeCorrecaoDeOrganizacao,
  type ComandoDeNovaArea,
  type ComandoDeNovaCategoria,
  type ComandoDeReordenacao,
} from "./configuracao";
export {
  AreaInvalida,
  AreaNaoEncontrada,
  CategoriaNaoEncontrada,
  CodigoPublicoEmUso,
  CodigoPublicoNaoEncontrado,
  ContatoDuplicado,
  ConviteIndisponivel,
  ConvitePessoalNaoVale,
  EtiquetaNaoEncontrada,
  JaVinculado,
  ListaDesatualizada,
  NomeDeAreaDuplicado,
  NomeDeCategoriaDuplicado,
  PedidoDeEntradaPendente,
  PedidoJaDecidido,
  PedidoNaoEncontrado,
  PessoaComContaNaoEditavel,
  UltimoGestor,
  VinculoComHistorico,
  VinculoNaoEncontrado,
} from "./erros";
export type {
  AlteracaoDeConfiguracao,
  AreaAtualizada,
  AreaLida,
  CategoriaLida,
  ChaveDeConfiguracao,
  ConfiguracaoLida,
  ContagemDaLista,
  ContatoLido,
  ContatoParaEscrita,
  ConvitePessoalPorToken,
  ConvitePessoalVivo,
  CorrecaoDeArea,
  CorrecaoDeCategoria,
  CorrecaoDeOrganizacao,
  DadosDaCorrecao,
  DadosDoCadastro,
  EtiquetaLida,
  ImpedimentoDeRemocao,
  LeituraDeConvitesPessoais,
  MudancaDeConfiguracaoLida,
  NovaArea,
  NovaCategoria,
  NovaOrganizacao,
  OrdemNaCriacao,
  OrganizacaoCriada,
  OrganizacaoDoConvite,
  OrganizacaoLida,
  PedidoDaPessoa,
  PedidoDeEntradaLido,
  PedidoDeEntradaRegistrado,
  PedidoDeRotulos,
  PosicaoNaLista,
  RegrasDaOrganizacao,
  Reordenacao,
  RepositorioDeConvites,
  RepositorioDeConvitesPessoais,
  RepositorioDeOrganizacoes,
  RepositorioDePedidosDeEntrada,
  RepositorioEscopadoDaConfiguracao,
  RepositorioEscopadoDaOrganizacao,
  RepositorioEscopadoDeAreas,
  RepositorioEscopadoDeCategorias,
  RepositorioEscopadoDeConvitesPessoais,
  RepositorioEscopadoDeEtiquetas,
  RepositorioEscopadoDePedidosDeEntrada,
  RepositorioEscopadoDeVinculos,
  RepositorioGlobalDePedidosDeEntrada,
  ResultadoDaAprovacao,
  ResultadoDaAtribuicaoDeEtiqueta,
  ResultadoDaCorrecao,
  ResultadoDaRecusa,
  ResultadoDaRemocao,
  ResultadoDaRevogacao,
  ResultadoDaReordenacao,
  ResultadoDaRetiradaDeEtiqueta,
  ResultadoDeCorrecaoDeArea,
  ResultadoDeCorrecaoDeCategoria,
  ResultadoDeCriacaoDeArea,
  ResultadoDeCriacaoDeCategoria,
  ResultadoDoApagarEtiqueta,
  ResultadoDaLigacao,
  ResultadoDoAceite,
  ResultadoDoCadastro,
  ResultadoDoPedidoDeEntrada,
  RotulosDoSolicitante,
  VinculoLido,
} from "./portas";
